spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Tan1763344790
    url: jdbc:mysql://121.199.76.157:3306/procurement_system?useSSL=false&serverTimezone=Asia/Shanghai
  pagehelper:
    helperDialect: mysql
    reasonable: false  #开启优化，如果开启优化，在分页页码结果没有数据的时候,会显示有数据的页码数据
    supportMethodsArguments: true #是否支持接口参数来传递分页参数，默认false
    #pageSizeZero: false #pageSize=0 返回所有
    params: count=countSql

